### ISSUE TITLE
Support for PKI Backend ?

### ISSUE THREAD

**Issue by alwaysastudent** [hashicorp/cf-vault-service-broker#10]
Like generic or transit backends , do you think the PKI backend should also be established with mounts and policies on the servers and the same be populated on the VCAP_SERVICES ?

**Comment by sethvargo** [comment]
Hi @alwaysastudent 

Unlike generic or transit, the PKI backend requires significant configuration that we (the broker) cannot possibly know in advance. This is also why we recommend running Vault as its own service. As a Vault administrator, you can configure it to enable the PKI backend with the proper things.

**Comment by alwaysastudent** [comment]
@sethvargo - So do you recommend to have the policy manually modified for the token generated when the broker service instance is created ?

**Comment by sethvargo** [comment]
Hi @alwaysastudent 

You can attach multiple policies to the token during generation, so you would change the policy that is applied when the broker creates a token.

**Comment by alwaysastudent** [comment]
@sethvargo - I didn't understand. Are you saying an operator should grab hold of the service instance id  and go to the vault server and edit the policy for the same ?
