### ISSUE TITLE
The id field of the plan does not pass a guid regex check

### ISSUE THREAD

**Issue by emaildanwilson** [hashicorp/cf-vault-service-broker#13]
Some implementations of the open service broker api check to make sure the id field of plan objects match regex `[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?` Would it be possible to switch https://github.com/hashicorp/cf-vault-service-broker/blob/master/broker.go#L301 to `ID:          fmt.Sprintf("%s-%s", b.serviceID, VaultPlanName),` in order to support this validation?

**Comment by sethvargo** [comment]
Hey @emaildanwilson 

We would be happy to make that switch, but I'd like to link to some external docs in the code for future-proofing. Do you have a link to some of the implementations that require this?

**Comment by emaildanwilson** [comment]
Here is the error I'm getting from the [kubernetes implementation](https://github.com/kubernetes-incubator/service-catalog/blob/7295dad7fcae1d718e6cb06d928d8d5c38ef2bf5/pkg/apis/servicecatalog/validation/serviceclass.go#L40) of the OSB: `message: ‘Error syncing catalog from Broker. Error reconciling serviceClass “hashicorp-vault”
      (broker “vault-broker”): ServiceClass.servicecatalog.k8s.io “hashicorp-vault”
      is invalid: plans[0].externalID: Invalid value: “0654695e-0760-a1d4-1cad-5dd87b75ed99.shared”:
      [a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])? (e.g. ‘'123-abc’‘,  or ‘'456-DEF’‘, regex
      used for validation is ‘’my-name’‘)'`

There may be others since GUID is suggested for this field. Since it's not strictly enforced or spelled out in detail in the OSB api I understand if you don't want to change this. I'm also asking if the requirement can be relaxed on the k8s side.

**Comment by jefferai** [comment]
Do you have a link to the docs that suggest using a GUID? If that's what the docs say, I think the preferable course of action would be to press kubernetes to allow values following that suggestion

**Comment by sethvargo** [comment]
The [Pivotal docs](http://docs.pivotal.io/pivotalcf/1-8/services/api.html#PObject) say:

> `id` - An identifier used to correlate this plan in future requests to the catalog. This must be unique within Cloud Foundry, using a GUID is recommended.

I looked at a few brokers online, and they all follow the model of `<broker-id>.<plan-name>` like `acb56d7c-XXXX-XXXX-XXXX-feb140a59a66.shared`.

**Comment by jefferai** [comment]
OK. So basically Kubernetes won't work with any of those, and as such I'm not inclined for us to stop using the recommended behavior when Kubernetes is simply out of spec.

**Comment by emaildanwilson** [comment]
Thank you.
Closing this.
