### ISSUE TITLE
Broker crashes after starting

### ISSUE THREAD

**Issue by jgeorge300** [hashicorp/cf-vault-service-broker#4]
Successfully installed and configured vault-service-broker. I was able to create a service and bind it to an application. The application was able to successfully authenticate and retrieve secrets from its space. At some point the service broker went down. When I tried to restart the broker, the broker's token had expired. Created a new token and restaged. The broker now crashes shortly startup after it fails to renew a token. I haven't been able to locate the token via the token's accessor. How do I remove the bad token or correct the permission? 
 
The broker's log:
```
2017-03-22T11:35:41.54-0400 [CELL/0]     OUT Creating container
2017-03-22T11:35:41.90-0400 [CELL/0]     OUT Successfully created container
2017-03-22T11:35:42.61-0400 [CELL/0]     OUT Starting health monitoring of container
2017-03-22T11:35:42.67-0400 [APP/0]      OUT [INFO] starting broker
2017-03-22T11:35:42.67-0400 [APP/0]      OUT [DEBUG] creating mounts map[string]string{"cf/broker":"generic"}
2017-03-22T11:35:42.79-0400 [APP/0]      OUT [DEBUG] restoring bindings
2017-03-22T11:35:42.79-0400 [APP/0]      OUT [DEBUG] listing directory "cf/broker/"
2017-03-22T11:35:42.79-0400 [APP/0]      OUT [INFO] sleeping for 9m31s
2017-03-22T11:35:42.81-0400 [APP/0]      OUT [INFO] restoring info for instance 06431075-2718-449b-9186-3cf06e3d5c12
2017-03-22T11:35:42.83-0400 [APP/0]      OUT [DEBUG] decoding bind data from cf/broker/06431075-2718-449b-9186-3cf06e3d5c12
2017-03-22T11:35:42.83-0400 [APP/0]      OUT [DEBUG] listing directory "cf/broker/06431075-2718-449b-9186-3cf06e3d5c12/"
2017-03-22T11:35:42.84-0400 [APP/0]      OUT [INFO] restoring bind for instance 06431075-2718-449b-9186-3cf06e3d5c12 for binding dc9cd23b-0b83-4ad4-960f-3f3bf2d0d573
2017-03-22T11:35:42.84-0400 [APP/0]      OUT [DEBUG] reading bind from cf/broker/06431075-2718-449b-9186-3cf06e3d5c12/dc9cd23b-0b83-4ad4-960f-3f3bf2d0d573
2017-03-22T11:35:42.86-0400 [APP/0]      OUT [DEBUG] decoding bind data from cf/broker/06431075-2718-449b-9186-3cf06e3d5c12/dc9cd23b-0b83-4ad4-960f-3f3bf2d0d573
.
.
.
2017-03-22T11:35:43.27-0400 [APP/0]      OUT [INFO] restored 6 binds and 8 instances
2017-03-22T11:35:43.28-0400 [APP/0]      OUT [INFO] starting server on :8080
2017-03-22T11:35:44.66-0400 [CELL/0]     OUT Container became healthy
2017-03-22T11:35:47.86-0400 [APP/0]      OUT [DEBUG] renewing token with accessor 81199bc3-22b6-0337-3c56-b66fd8c3a03b
2017-03-22T11:35:47.90-0400 [APP/0]      OUT [ERR] token renewal failed: Error making API request.
2017-03-22T11:35:47.90-0400 [APP/0]      OUT URL: PUT https://vault.dev:443/v1/auth/token/renew
2017-03-22T11:35:47.90-0400 [APP/0]      OUT Code: 403. Errors:
2017-03-22T11:35:47.90-0400 [APP/0]      OUT * permission denied
2017-03-22T11:35:47.90-0400 [APP/0]      OUT Exit status 1
2017-03-22T11:35:47.91-0400 [CELL/0]     OUT Exit status 0
2017-03-22T11:35:47.94-0400 [CELL/0]     OUT Destroying container
2017-03-22T11:35:47.95-0400 [API/1]      OUT App instance exited with guid f1e936a3-194e-4002-95d0-796045e4f101 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>7, "crash_timestamp"=>1490196947934464113, "version"=>"9ef948c3-b7b6-4d46-b273-ff95054d64ba"}
2017-03-22T11:35:48.37-0400 [CELL/0]     OUT Successfully destroyed container
```

**Comment by sethvargo** [comment]
Hi @jgeorge300 

This is definitely a bug (and we'll try to fix it), but in the meantime you should be able to recover by deleting that stale bind data manually in Vault:

```
$ vault delete cf/broker/06431075-2718-449b-9186-3cf06e3d5c12/dc9cd23b-0b83-4ad4-960f-3f3bf2d0d573
```

**Comment by jgeorge300** [comment]
I had to delete all of the bindings. (There were several I removed from the above log.) My app was not able to authenticate. I tried to unbind my app from the vault-service but received the following error:
```
$ cf us complete vault-service
Unbinding app complete from service vault-service in org prime / space jgeorge as jgeorge...
Unexpected Response
Response code: 502
CC code:       10001
CC error code: CF-ServiceBrokerBadResponse
Request ID:    ca8964e5-de70-4ef0-6eb6-86a5472cc4d0
Request ID:    ca8964e5-de70-4ef0-6eb6-86a5472cc4d0::a8f86683-94bb-43b5-9d28-d1c1430cb6fd
Description:   Service instance vault-service: Service broker error: missing bind info for unbind for cf/broker/2ecfe85b-f33b-48df-9877-674bc1995553/43502046-97dc-4881-8f38-e2eeaf98e25b
```

I purged the service instance, re-created and then rebound it to the app. At that point, my app could access its secrets.

**Comment by jgeorge300** [comment]
Our vault-broker crashed again over the weekend. Getting the same issue as above. Trying to determine the cause of the initial crash of the broker but the logs have already cycled out of CF. Checking our central logging system.

**Comment by jgeorge300** [comment]
Reviewed the broker logs, it appears to have failed to renew its token with the vault server. It crashed after that. The broker is using an orphan token that is set for unlimited renewals.

**Comment by sethvargo** [comment]
Hi @jgeorge300 

Is that a periodic token?

**Comment by jgeorge300** [comment]
Yes, it is a periodic token. Created with the command and policies listed in README under the "Broker Vault Token Permissions" section.

**Comment by sethvargo** [comment]
Hi @jgeorge300 

I'm very sorry this is causing issues. It would be very helpful if you could share:

1. Version of Vault
1. Version of this broker (sha is fine)
1. Logs from the broker
1. Logs from Vault
1. Command you ran to generate the Vault token

**Comment by jgeorge300** [comment]
@sethvargo 

1. 0.6.4
2. bea3e0e1c4f1bc719ec46f330a8a91f13daa2cc7
3. A bit difficult to extract the broker log from CF but I believe this is the log message when the broker first crashes:
```
<6>2017-03-25T05:26:39Z 863a0445-8a7a-44f9-7c66-07a687cb0d41 doppler[20]: {"cf_app_id":"f1e936a3-194e-4002-95d0-796045e4f101","cf_app_name":"vault-broker","cf_org_id":"7433c1b0-c9cb-467c-91ed-903c01dca2db","cf_org_name":"system","cf_origin":"firehose","cf_space_id":"98900330-b375-40fb-96e0-ed07db4ba6c4","cf_space_name":"vault-broker","deployment":"cf","event_type":"LogMessage","ip":"10.0.32.25","job":"diego_cell","job_index":"be4da6d7-a956-4a8a-85e3-371639736023","level":"info","message_type":"OUT","msg":"[DEBUG] renewing token with accessor e1be0d56-4ac6-df6b-9852-28fac9eb24e3","origin":"rep","source_instance":"0","source_type":"APP","time":"2017-03-25T05:26:39Z","timestamp":1490419599009397681}
<6>2017-03-25T05:26:39Z 863a0445-8a7a-44f9-7c66-07a687cb0d41 doppler[20]: {"cf_app_id":"f1e936a3-194e-4002-95d0-796045e4f101","cf_app_name":"vault-broker","cf_org_id":"7433c1b0-c9cb-467c-91ed-903c01dca2db","cf_org_name":"system","cf_origin":"firehose","cf_space_id":"98900330-b375-40fb-96e0-ed07db4ba6c4","cf_space_name":"vault-broker","deployment":"cf","event_type":"LogMessage","ip":"10.0.32.25","job":"diego_cell","job_index":"be4da6d7-a956-4a8a-85e3-371639736023","level":"info","message_type":"OUT","msg":"[ERR] token renewal failed: Error making API request.","origin":"rep","source_instance":"0","source_type":"APP","time":"2017-03-25T05:26:39Z","timestamp":1490419599096660577}```
4. Vault log 
```
2017/03/24 21:22:38.732455 [INFO ] expire: revoked lease: lease_id=auth/approle/login/d83ae44ce1d27b89e456825e0cb16a77d491c525
2017/03/24 22:22:35.343910 [INFO ] expire: revoked lease: lease_id=auth/approle/login/fc780318c5bbd1d4fdcd7dc2821938955bec7aad
2017/03/25 05:42:16.745317 [INFO ] expire: revoked lease: lease_id=auth/token/create/522dd5a3670ca8e14780a3bc9ae04c7f3346ea29
2017/03/25 16:43:28.356290 [INFO ] expire: revoked lease: lease_id=auth/token/create/fdf03c9714e33251664203562ebdfd32f7f7cb67
```
5. vault token-create -period="30m" -orphan -policy=cf-broker

Audit Log:
```
Mar 25 05:26:53 vault[11989]: {"time":"2017-03-25T05:26:53Z","type":"request","auth":{"client_token":"","accessor":"","display_name":"","policies":null,"metadata":null},"request":{"id":"fecd7c6d-f4ea-12d7-fabf-9b56edab677a","operation":"update","client_token":"hmac-sha256:0f265f4cb241803b37184bd71c8ed8af4d530af6f8db904718d8b7e437b8b4ab","client_token_accessor":"hmac-sha256:fb9de108036500131e85cb7a2b7ea86de5823b65e80f0799f0e2df14d8a7c7fb","path":"auth/token/renew","data":{"increment":"hmac-sha256:abc259ffed51f04c1829ccc69a2da5236669acbcac739dfcea15c2fe310d469a","token":"hmac-sha256:de71951b2132c6386ecfdc24a853334b84c698170369e1d3a016d2f32926bf88"},"remote_address":"10.10.10.135","wrap_ttl":0},"error":"permission denied"}
Mar 25 05:26:53 vault[11989]: {"time":"2017-03-25T05:26:53Z","type":"response","error":"1 error occurred:\n\n* permission denied","auth":{"client_token":"","accessor":"","display_name":"","policies":null,"metadata":null},"request":{"id":"fecd7c6d-f4ea-12d7-fabf-9b56edab677a","operation":"update","client_token":"hmac-sha256:0f265f4cb241803b37184bd71c8ed8af4d530af6f8db904718d8b7e437b8b4ab","client_token_accessor":"hmac-sha256:fb9de108036500131e85cb7a2b7ea86de5823b65e80f0799f0e2df14d8a7c7fb","path":"auth/token/renew","data":{"increment":"hmac-sha256:abc259ffed51f04c1829ccc69a2da5236669acbcac739dfcea15c2fe310d469a","token":"hmac-sha256:de71951b2132c6386ecfdc24a853334b84c698170369e1d3a016d2f32926bf88"},"remote_address":"10.10.10.135","wrap_ttl":0},"response":{"data":{"error":"hmac-sha256:fb4ebb84125dffa2a04236e68f261e36ecfc059e92e107399ff858fe6aff05a4"}}}
```

**Comment by jefferai** [comment]
My guess from the error being permission denied is that the renewal should be using the `auth/token/renew-self` endpoint, which is allowed in the `default` policy, but instead is using the `auth/token/renew` endpoint which is not allowed by `default`.

**Comment by jefferai** [comment]
I think the issue is at https://github.com/hashicorp/cf-vault-service-broker/blob/master/broker.go#L681

**Comment by sethvargo** [comment]
@jefferai 

Hmm so should we "auth" as that token and then use renewSelf? That token is not the one that the broker is using, it's the token that was given to application instances. The broker is responsible for renewing those tokens.

**Comment by jefferai** [comment]
Oh, I see. I think you have two options:

1) When renewing a token, set that token as the client's current token and then call RenewSelf (not sure if there are concurrency issues here)
2) Ensure that the token for the broker has an ACL allowing access to `auth/token/renew`

From a customer perspective the former is likely more transparent but if the client is being used for lots of calls separately than there may be concurrency issues since the token is global to the client.

**Comment by jgeorge300** [comment]
I updated the broker token to have create/update permissions to auth/token/renew. The broker is still running.

**Comment by jgeorge300** [comment]
Spoke too soon. The broker crashed later in the day with the same reason. The broker stays up for 48-72 hours.

**Comment by armon** [comment]
@jgeorge300 Looking into now, it looks like we have a `log.Fatalf` that is causing the broker to die on renew failure. Fixing that now so that the broker doesn't exit, but looking into the separate issue of why renewal is failing. I'll try to get a new build for you tonight!

**Comment by armon** [comment]
@jgeorge300 The fix of the `Fatalf` is in a0dc4c8. I'll keep looking into why we are getting the error. Thanks for helping us debug this!

**Comment by jefferai** [comment]
@armon See further up, I describe the issue and how it can be fixed. Although the client isn't thread safe from a modifying-token perspective, perhaps cloning the config into a new client using the token, then calling renew-self, will work.

**Comment by jgeorge300** [comment]
@armon I've pulled the latest code and installed it. I'll let you know what happens.

**Comment by jgeorge300** [comment]
Running successfully for 5 days.

**Comment by jgeorge300** [comment]
Still working. I think we can consider this fixed.

**Comment by armon** [comment]
@jgeorge300 Great, thanks!

**Comment by jgeorge300** [comment]
Not sure if this is related or not. The broker had been running successfully since I updated it with the latest code. According to our logs, the broker crashed again ~32 days after being updated. The message in the log is:

```
[INFO] renewing vault token
[ERR] renew-token: error renewing vault token: Get https://vault:443/v1/auth/token/lookup-self: dial tcp XXX.XXX.XXX.XXX:443: getsockopt: connection refused
```
The system log shows the token being renewed every 15 minutes prior to this. The broker's token was a periodic token so the system default ttl shouldn't have come in to play. 

I recreated a periodic token and the token lookup returns:
$ vault token-lookup XXX                          
```
Key                     Value
---                     -----
accessor                XXX
creation_time           1494862293
creation_ttl            3600
display_name            token
explicit_max_ttl        0
id                      XXX
last_renewal_time       1495024367
meta                    <nil>
num_uses                0
orphan                  true
path                    auth/token/create
period                  3600
policies                [cf-broker default]
renewable               true
ttl                     2246 
```

**Comment by sethvargo** [comment]
Hi @jgeorge300 

The "32 days" seems oddly suspicious given that's the default token TTL. Could you please confirm that the original token was periodic? Additional debug output would be very helpful 😄

**Comment by jgeorge300** [comment]
Vault just returns a bad token when I do a token lookup on the original token. I reviewed my bash history to check how I created the token to rule out PEBCAK prior to posting. As far as I can tell, it was a periodic token.

Prior to the renewal error, the broker log has every 15m or so.
```
[INFO] renewing vault token
[INFO] sleeping for 14m52s
```

Found the following additional messages:

2017-05-14T05:20:19Z [INFO] renewing vault 
2017-05-14T05:20:19Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55ba2cc1280d]
2017-05-14T05:20:19Z [ERR] renew-token: error renewing vault token: Get https://vault:443/v1/auth/token/lookup-self: dial tcp XXX.XXX.XXX.XXX:443: getsockopt: connection refused
2017-05-14T05:20:19Z [ERR] renew-token: secret has no data: Get https://vault:443/v1/auth/token/lookup-self: dial tcp XXX.XXX.XXX.XXX:443: getsockopt: connection refused
2017-05-14T05:20:19Z main.(*Broker).renewVaultToken(0xc420123a20)
2017-05-14T05:20:19Z panic(0x55ba2d237520, 0xc42000c0b0)
2017-05-14T05:20:19Z panic: runtime error: invalid memory address or nil pointer dereference
2017-05-14T05:20:19Z \t/tmp/gobuildpack.gopath445361536/.go/src/github.com/hashicorp/cf-vault-service-broker/broker.go:725 +0x17d
2017-05-14T05:20:19Z created by main.(*Broker).Start
2017-05-14T05:20:19Z goroutine 6 [running]:
2017-05-14T05:20:19Z [WARN] failed to renew token: Put https://vault:443/v1/auth/token/renew-self: dial tcp XXX.XXX.XXX.XXX:443: getsockopt: connection refused
2017-05-14T05:20:19Z \t/tmp/cache/go1.7.5/go/src/runtime/panic.go:500 +0x1a5
2017-05-14T05:20:19Z Exit status 2
```

**Comment by jefferai** [comment]
It looks like you had a connectivity outage between Vault and the broker that lasted longer than your token's period.

**Comment by jgeorge300** [comment]
Token period was set to 1 hour. The logs show the broker renewing the token every 15 minutes prior to the error. If the broker encounters a network error does it try to reconnect?

**Comment by jefferai** [comment]
If the network outage lasted an hour, regardless of whether it tries to reconnect or not, it would be beyond the token's TTL.

**Comment by jgeorge300** [comment]
Correct, but the token has a ttl of an hour. It was renewed successfully 15 minutes prior to the error. So it should still had another 45 minutes tl and another possible 3 renewal attempts.

**Comment by jefferai** [comment]
@jgeorge300 I don't think you're actually running the latest code...the line number in the broker crash from your log above doesn't correspond to a line where there can be a nil pointer.

**Comment by cah-josephgeorge** [comment]
Looks like I was a commit behind, pushed the latest commit to pcf.
