### ISSUE TITLE
How to add self signed cert into the trust store ?

### ISSUE THREAD

**Issue by alwaysastudent** [hashicorp/cf-vault-service-broker#7]
Is there a way to trust the self signed cert that is being used in the vault service from this broker ?

**Comment by sethvargo** [comment]
Hi @alwaysastudent 

I'm not sure what you're asking here. We do not do any certificate generation in this service broker.

**Comment by alwaysastudent** [comment]
I have enabled TLS in the vault server with a self signed certificates. How can I tell the broker to use the specified certificate file to verify the peer ?  I can work around this by setting an env variable. But not sure it is ideal.
```
cf set-env vault-broker VAULT_SKIP_VERIFY  "true"
```

**Comment by sethvargo** [comment]
Hi @alwaysastudent 

You would need to set some of the following environment variables in the broker to point to a valid certificate:

```
VAULT_CACERT
VAULT_CAPATH
VAULT_CLIENT_CERT
VAULT_CLIENT_KEY
VAULT_TLS_SERVER_NAME
```
