### ISSUE TITLE
What is the difference between the cf-community vault-broker versus this ?

### ISSUE THREAD

**Issue by alwaysastudent** [hashicorp/cf-vault-service-broker#9]
Can you please let us know which one is most relevant  ?
https://github.com/cloudfoundry-community/vault-broker

**Comment by sethvargo** [comment]
Hi @alwaysastudent 

Thank you for reaching out. Looking at the broker you linked, the main difference appears to be the scope and setup. Our version of the broker provides multiple mounts for sharing application secrets, service secrets, and organization secrets. The one linked seems to have limited their scope to application secrets.

Ours is also designed to be run inside _or_ outside of CloudFoundry. Meaning you could run this on a hosted service like Heroku - it doesn't need to be run in CF directly. This project is officially supported by HashiCorp, the company that makes Vault.

On the flip size, the other project is a bit older (more mature) and has more stars and watchers at the time of this writing.

Please let me know if you have any additional questions.
